import {
  UserGroupIcon,
  Cog6ToothIcon,
  TrashIcon,
  DocumentPlusIcon,
  ArrowUpTrayIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  LinkIcon,
  StarIcon,
  ArchiveBoxIcon,
  DocumentArrowDownIcon,
  LanguageIcon,
  KeyIcon,
  QuestionMarkCircleIcon,
  ChatBubbleLeftRightIcon,
  ArrowPathIcon,
  SunIcon,
  ComputerDesktopIcon,
  ArrowLeftIcon,
  ArrowLeftStartOnRectangleIcon,
} from "@heroicons/vue/24/outline";

export const INITIAL_COMMANDS = [
  {
    id: "1",
    label: "Create New Document",
    description: "Start with a blank slate",
    icon: DocumentPlusIcon,
    shortcut: ["⌘", "N"],
  },
  {
    id: "2",
    label: "Import File",
    description: "Upload PDF, MD, or Word",
    icon: ArrowUpTrayIcon,
    shortcut: ["⌘", "I"],
  },
  {
    id: "3",
    label: "Search Workspaces",
    description: "Quickly switch between teams",
    icon: MagnifyingGlassIcon,
    shortcut: ["⌘", "S"],
    children: "workspaces",
  },

  {
    id: "4",
    label: "Appearance Settings",
    description: "Themes and layouts",
    icon: MoonIcon,
    children: "appearance",
  },
  {
    id: "5",
    label: "Advanced Actions",
    description: "API keys and dangerous operations",
    icon: Cog6ToothIcon,
    children: "advanced",
  },

  {
    id: "6",
    label: "Copy Link",
    description: "Copy current page URL",
    icon: LinkIcon,
    shortcut: ["⌘", "L"],
  },
  {
    id: "7",
    label: "Share with Team",
    description: "Manage permissions",
    icon: UserGroupIcon,
  },
  {
    id: "9",
    label: "Add to Favorites",
    description: "Save for later",
    icon: StarIcon,
  },
  {
    id: "10",
    label: "Archive Page",
    description: "Move to archive",
    icon: ArchiveBoxIcon,
  },
  {
    id: "11",
    label: "Export as PDF",
    description: "Download static version",
    icon: DocumentArrowDownIcon,
  },
  {
    id: "12",
    label: "Change Language",
    description: "Interface localization",
    icon: LanguageIcon,
  },
  {
    id: "13",
    label: "Keyboard Shortcuts",
    description: "View all hotkeys",
    icon: QuestionMarkCircleIcon,
    shortcut: ["?"],
  },
  {
    id: "14",
    label: "Contact Support",
    description: "Talk to a human",
    icon: ChatBubbleLeftRightIcon,
  },
  {
    id: "15",
    label: "Check for Updates",
    description: "Version 2.4.0",
    icon: ArrowPathIcon,
  },
  {
    id: "16",
    label: "Log Out",
    description: "Sign out of your account",
    icon: ArrowLeftStartOnRectangleIcon,
    confirm: "logout",
  },
];

export const SUB_MENUS = {
  workspaces: [
    {
      id: "w1",
      label: "Workspace Alpha",
      description: "Team Alpha workspace",
      icon: UserGroupIcon,
      shortcut: ["⌘", "1"],
      isBack: false,
    },
    {
      id: "w2",
      label: "Workspace Beta",
      description: "Team Beta workspace",
      icon: UserGroupIcon,
      shortcut: ["⌘", "2"],
      isBack: false,
    },
    {
      id: "w3",
      label: "Workspace Gamma",
      description: "Team Gamma workspace",
      icon: UserGroupIcon,
      shortcut: ["⌘", "3"],
      isBack: false,
    },
    {
      id: "w-back",
      label: "Back to Main Menu",
      icon: ArrowLeftIcon,
      shortcut: ["⌫"],
      isBack: true,
    },
  ],
  appearance: [
    {
      id: "a1",
      label: "Light Mode",
      description: "Switch to light theme",
      icon: SunIcon,
      isBack: false,
    },
    {
      id: "a2",
      label: "Dark Mode",
      description: "Switch to dark theme",
      icon: MoonIcon,
      isBack: false,
    },
    {
      id: "a3",
      label: "System Default",
      description: "Use system theme",
      icon: ComputerDesktopIcon,
      isBack: false,
    },
    {
      id: "a-back",
      label: "Back to Main Menu",
      icon: ArrowLeftIcon,
      shortcut: ["⌫"],
      isBack: true,
    },
  ],
  advanced: [
    {
      id: "d1",
      label: "Regenerate API Key",
      icon: KeyIcon,
      dangerous: false,
      confirm: "regenerate-key",
    },
    {
      id: "d2",
      label: "Delete Workspace",
      icon: TrashIcon,
      dangerous: true,
      confirm: "delete-workspace",
    },
    {
      id: "d-back",
      label: "Back to Main Menu",
      icon: ArrowLeftIcon,
      shortcut: ["⌫"],
      isBack: true,
    },
  ],
};
